'use strict';

var startupAscii = angular.module('startup-ascii', []);

startupAscii.factory('startup-ascii-printer', function(){

	var images = {
		bill: function(){console.log('                   ~=~~~--                                  \n                ??I+=+I+?+?7I??=                            \n             =?I7$I$Z7II??II?7$$I?=                         \n            ?II77$$7Z$7I?+?+=++?$7$7+=                      \n          ~II?I$$777$77I?+=======+I$Z7?=                    \n         ~+7II77777I???+~==+=+=====+?II~+                   \n        ~+I77I???I+++=+=======+=+==+=+??~~                  \n       ~~+7??+++==+=+========++++==+++++==                  \n      ~~+II???++?++==~~~~~=~=====+=+++?++~=                 \n      +?7$???????+==~~-~~~~~~+====+==+++++~+~               \n     ~+I7III??+==+===~==~~=~~==~=++==+++??=~~               \n     ?IIIII7???++====~=~=====~+=I+====++?I?==~              \n     ?II77III??++========+===~=~+=+=++++?+II++~             \n     ?7I777III??++++?=======~==+?I7??+=++++?+?~-==          \n     ?777I7I???+++==+++======?Z$OZ$I77?++++?+=I+?$I         \n     ~77$777II?I++=++====++=+?77I??+?????+==??++I??+        \n      ?7$$77II?????++?++==?+?77IDODD$8ZI?=+=+?+?I+++        \n       ?$$$77??II?7$$7I??===+77ZZ$$Z?7??+~==++??$I??        \n       =7$Z7777Z$OZ$I?I$$I==+?=????+?+??===+=++??I?++       \n        7OO$778O$I+IO$8$I$??=???????+++?=++++++?=?+?+       \n        ?7O$$7Z$I7DDMZ+7+7I?=+??++++++++++????????=?=       \n        ?$Z$$7$$Z8Z?I???I7I?++++I?==+===+?????++?+?=+       \n        7O7Z7777Z7II?7??I7II+==?I+7?+==+++?????+??==+       \n        $$$$77????I??7?+IZZI++?I777+7I+++???????I?II        \n         OO$$7I?++??I??+?777$$$$$Z?++++???I???I???          \n         7$Z7$77III?I???7$$8OOO$I?+?++++?II??????I          \n          $$Z$$$77II??IIIII77?II???I?III??IIII?III          \n          ?7ZZ$$$$$7II?+I?III???IZDO?I77I???IIIII7          \n           Z7$$$$7$$7I$I?I777DZI+?II???I???IIII7$$          \n            7$ZOZ77777II7IZ$777$7I7+???++II7$77$OZZDN       \n             I7ZZ$$II77I77$I?IIII?+?+++???7$ZZZOZ7IZMN8     \n                6Z$$7777?I$I7???++?+++???IZOOOOZ777IDMNNN8  \n                  ZZ$$7$I777?III????II?IIZOOOOZ$77I?NNNMNNNN\n                   ?Z$$$$7$77IIIIII77ZZOOOOOOZ$7I7$INMMMNMMN\n                    ~ZZZZZZZ$$$ZZZOOOZOZOZZZZ$77I7?IMMNMMMMN\n                     ~OOOOOOOOO8OOOOZOOOOOOZ77II7IIZMMMMMMMM\n                       OOOO8OOOOOOOZOOOZOO$$7I77II7?MNMMMMMM\n                        OOOOOO8OOOOOOOZZZ$7777IIII$7MMMMMMMM\n                        +OO8OOOOOOOZOZZ$Z$7$$III7$?7MMNMMMMM\n                       &&88O8OO8OOZOZZ$$Z$Z$77$I$II7MMMMMMMM\n                     &&&M88O8OOOOOOZOZ$ZZZ$$777$III7MMMMMMNM\n                  &&&&OMMDM88OZO8OOOOOOOZZ$$77$ZII77MMMMMMMM\n               7&7778MMMMNDM8OOO888OOZOOZZZ$$$OII7$OMMMMMMMM\n            &&&&&&8MMMMMMM8DM88OOO8ZOOZZZOO$$$7I7Z?7OZZMMMMM\n          8&&&&8DMMMMMMMMMOOMMD88OOOZOZZZZOZZZ7I$Z7MMMMMMMNM \n');}, 
milhouse: function(){console.log('                             NZZZZZZZZZZ.                   \n                           NZZZZZZZZZZZZZZO                 \n                          ZZZZZZZZZZZZZZZZZZZ$              \n                        OZZZZZD???????OZZZZZZZZ=            \n                        ZZZ8??????????????OZZZZZZ           \n                       8Z:=??????????????????I8ZZZ          \n                       ?  ZZI???????DZZZZN???IZZZZD         \n                          7?????????????IO$??OZZZZZZ        \n  The House Always       ,??????????????????IZZZZZZZ        \n      Wins.             :ND?????????I   MI??ZZZZZZZN        \n                      .    NO??????      DO+ZZZZZZZ         \n                      D  .  8MI??OZ   .  :OMZZZZZZ8         \n                       .   ????????D     8OZNOOONZ          \n                        ,O???????????$8MZO$ZZZZZZNOM        \n                         $??????????????????????D 8O        \n                         ????????????????????O$??.          \n                         ???????????????????????I           \n??????D7                  ????????O??????????8.             \n ~O?????????????D?        .??I??????????????8               \n    ????????????????????8I?????????????$????:               \n   N??I???????????????????????=IO$??????????7               \n   I??????????????????????????:::~??????????M:::::::D       \n               8$?????????????::::,????????Z::::::::::      \n                      =D?????8:::::Z????O,:::::::::::$+     \n                           :::::::~::::::::::::88::::D???N  \n                           N,:::::M::::::::::D????O::?????$ \n                                   :::::::::$??????????????N\n                                   =::::::::$I??????????????\n                                   ,::::::::::?????????????D\n                                   :::::::::::ODDD????????  \n                                 $:::::::::::::::::::::,    \n                                 :::::::::::::::::::::::M   \n                                7:::::::::::::::::::::::Z   \n                                 ?:::::::::::::::::::DOOO   \n                                 NZZDZ,::::::::::OZOOOOOD   \n                              ,OOOOOONOOOOOOOOOOOOOOOOOO    \n                                                 .::+IIZ     \n');}, 
shark: function(){console.log('                                ....                        \n                              ...?7~.                       \n                            ..II77::7..                     \n                           .,77I7...7?.                     \n                         ..77I77.   .7.                     \n                        .~I7777...  .7:                     \n                       .77IIII.     .7+           ......    \n     .........       ..$77777..     .7+       .....7I7..    \n     ..I7I+..        .777II7...     .78.      ...7..7..     \n     ...7777.....  ..~7IMI77.       .7M.  .. ..7.. 7.       \n     ....77.77.    ..77IMM?.        .7M.  ...7,...I..       \n        .II7..7+....77777I7....ONM?,.7. ...7$. ..7...       \n        . 7I7...7...77II77.:MMMMDI M.7....I.....7..         \n        .. I7? ..+7777777=Z...  .,~=.I..I$. ...I..          \n         ...I7:....777777..     ....:+.7......7..           \n           .:7I..  .77I77..      . .7I7......7..            \n            .$77.....?777..      ...77... .7I...            \n           . .77I......I7.       ...77....77..              \n              .7I7....7I7        ...7I$..7...               \n             . .777..,I77.       . .I7I77....               \n                .I7777777. .     . .7777..                  \n                 .7777777?..     ...777=..                  \n                 ..777777I..     ..7777...                  \n                  ..777777I.     .777II. .                  \n                   .77777I77... .,I777I.                    \n                   ..I777777,....77I77I.                    \n                   ..I7777777...7777777.                    \n                    .I777777I7.7I7777I7..                   \n                    .I777777II77II77777..                   \n                   ..777777777777777777..                   \n                   ..I77777777777777777:.                   \n                    .I7777777..777777777.                   \n                    .7777777....77777777..                  \n                   .,I777II?.  ..7I7777I..                  \n                   .?I777I7.   ..,7777777.                  \n                   .7777777.     .777777I?...               \n                   .I77777..      .777I7II.... .            \n                   .777777..     . .7I7777I.....            \n                   .77777777...     .II77777777. ..         \n                   .777777777.      ..I777777I77~..         \n                   ....::~... .     ....=$77I77$...         \n                   .. .........          ...... ..           \n');}, 

	}
	return {
		print: function(image, text){
			try{
				images[image]();
			}
			catch(err){
				console.log('startup-ascii: error finding image for: ' + image + '. sorry for partying.');
			}
		}
	}
});

//startupAscii.directive();